### ISSUE TITLE
Data team: issue with invalid pr/issue query

### ISSUE THREAD

**Issue by HazelHilbert** [yvah/OpenSourceDynamics#43]
there seems to be an issue when you try to query an invalid pr/issue
I think it might be the fact that run_query returns a json weather or not the api call was successful

![Image](https://user-images.githubusercontent.com/98608198/221426012-e9edb5d1-f022-4fdb-8bff-49fae2c71540.png)

**Comment by yvah** [comment]
Finished the project.
